name: reff
description: reff description

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^0.11.4
  shared_preferences: ^0.5.8
  get_it: ^4.0.2
  provider: ^4.3.1
  mockito: ^4.1.1
  easy_localization: ^2.3.2
  google_fonts: ^1.1.0
  device_info: ^0.4.2+4
  uuid: ^2.2.0
  json_annotation: ^3.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^3.3.0



flutter:
  uses-material-design: true
  assets:
    - assets/translations/
