name: reff
description: reff description

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^0.11.4
  shared_preferences: ^0.5.8
  get_it: ^4.0.4
  flutter_hooks: ^0.13.0
  hooks_riverpod: ^0.5.1
  state_notifier: ^0.5.0
  mockito: ^4.1.1
  easy_localization: ^2.3.3
  google_fonts: ^1.1.0
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  material_design_icons_flutter: ^4.0.5345
  numberpicker: ^1.2.1
  searchable_dropdown: ^1.1.3
  connectivity: ^0.4.9
  reff_shared:
    path: ../reff_shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  cloud_firestore_mocks: ^0.4.6+1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
