name: reff
description: survey app
version: 1.0.0+8
author: Cihan Cengiz
environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^0.11.4
  shared_preferences: ^0.5.12
  tuple: ^1.0.3
  get_it: ^5.0.1
  flutter_hooks: ^0.14.1
  hooks_riverpod: ^0.11.1
  package_info: ^0.4.3
  state_notifier: ^0.6.0
  easy_localization: ^2.3.3
  google_fonts: ^1.1.0
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.1+2
  #  firebase_messaging: ^7.0.2
  material_design_icons_flutter: ^4.0.5655
  future_button: ^0.1.2
  flutter_inner_drawer: ^0.5.7+2
  cached_network_image: ^2.3.2+1
  searchable_dropdown: ^1.1.3
  connectivity: ^0.4.9+3
  flutter_shimmer: ^1.3.0
  animate_do: ^1.7.3
  percent_indicator: ^2.1.7+4
  badges: ^1.1.3
  flutter_spinkit: ^4.1.2+1
  titled_navigation_bar: ^4.1.0
  rive: ^0.6.2
  reff_shared:
    path: ../reff_shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  cloud_firestore_mocks: ^0.5.0+1
  effective_dart: ^1.2.4
  flutter_launcher_icons: ^0.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/rive/
    - assets/translations/
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"